name: Build Debian Packages

on:
  pull_request:
    branches:
      - main

env:
  DEBIAN_FRONTEND: noninteractive
  SPECIAL: bpo12

jobs:
  build-source:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Pre Checkout
        run: |
          rm -rf build-env
          apt-get -y update
          apt-get -y dist-upgrade
          apt-get -y install sudo git build-essential
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup
        run: |
          apt-get -y install $(cat debian/.debian-ci/build_source/build-depends)
          git config --global --add safe.directory $(realpath .)
      - name: Build from Source
        run: |
          $(pwd)/debian/.debian-ci/build_source/build-script
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-packages
          path: source-packages/

  build-binary:
    runs-on: ubuntu-latest
    needs: build-source
    container:
      image: debian:bookworm
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: source-packages
          path: source-packages/
      - name: Dependencies
        run: |
          apt-get -y update
          apt-get -y dist-upgrade
          apt-get -y install build-essential devscripts reprepro fakeroot
      - name: Setup
        run: |
          find source-packages
          upstream_version="$(head -n1 source-packages/version.txt)"
          if [ -z "$upstream_version" ]; then echo >&2 "Did not get package version from artifact."; exit 1; fi
          echo $upstream_version

          case "$SPECIAL" in
            "") echo "No special handling required";;
            bpo*)
              echo "deb https://deb.debian.org/debian bookworm-backports main" >> /etc/apt/sources.list.d/debian-bpo.list &&
              apt update &&
              srcchanges="$(ls -1 source-packages/tor_"$upstream_version"*"$SPECIAL"+*_src.changes)"
              ;;
            *) echo "Unknown special flag: $SPECIAL"; exit 1;;
          esac

          srcchanges="$(ls -1 source-packages/tor_"$upstream_version"*bookworm+*_src.changes)"
          echo "srcchanges: $srcchanges"
          if [ "$(echo "$srcchanges" | wc -l)" != 1 ] || [ -z "$srcchanges" ] ; then echo >&2 "Weird number of changes files found."; exit 1; fi

          case "$DOCKER_ARCH" in
            amd64) build_selector="-b";;
            *)     build_selector="-B";;
          esac

          echo "source changes file:"
          cat "$srcchanges"
          dsc="$(dcmd --dsc "$srcchanges")"
          echo "dsc file is ${dsc}"
          cat "$dsc"

          mkdir build-tree
          cd build-tree
          dpkg-source -x ../${dsc}
          cd tor-${upstream_version}
          apt-get -y build-dep .
          debuild -rfakeroot -uc -us "$build_selector"
          find ../../ | grep changes
          binchanges="$(ls -1 *.changes)"
          if [ "$(echo "$binchanges" | wc -l)" != 1 ] || [ -z "$binchanges" ] ; then echo >&2 "Weird number of changes files produced."; exit 1; fi
          cd ../../

          mkdir RESULT
          echo "dcmd..."
          dcmd ln -v "build-tree/${binchanges}" RESULT
          mkdir binary-packages
          echo "mv..."
          mv -v --no-target-directory RESULT binary-packages/"debian-${DOCKER_ARCH}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-packages
          path: binary-packages/
