name: Build Debian Packages

on:
  pull_request:
    branches:
      - main

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-source:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Pre Checkout
        run: |
          rm -rf build-env
          apt-get -y update
          apt-get -y dist-upgrade
          apt-get -y install sudo git build-essential
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup
        run: |
          apt-get -y install $(cat debian/.debian-ci/build_source/build-depends)
          git config --global --add safe.directory $(realpath .)
      - name: Build from Source
        run: |
          $(pwd)/debian/.debian-ci/build_source/build-script
