name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  image-tag: ${{ github.ref == 'refs/heads/main' && 'latest' || (github.ref_type == 'tag' && github.ref_name || github.sha) }}

jobs:
  build-and-push:
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            image-suffix: amd64
            runs-on: ubuntu-latest
          - name: linux/arm64
            image-suffix: arm64
            runs-on: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-image: ${{ secrets.DOCKER_BASE_REPO }}-${{ matrix.platform.image-suffix }}:${{ env.image-tag }}
          docker-platform: ${{ matrix.platform.name }}
          version: ${{ github.sha }}

  multiarch-push:
    runs-on: arm64
    needs: build-and-push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Multiarch push
        uses: ./.github/actions/multiarch-push
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-base-repo: ${{ secrets.DOCKER_BASE_REPO }}
          docker-tag: ${{ env.image-tag }}
